# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
        gradle_file_path: "./app/build.gradle",
  )
end

  desc "Build release app bundle"
 lane :build_bundle do
  gradle(
     task: "bundle",
     build_type: "Release"
   )
 end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    #1
    increment_vc
    #2
    build_bundle
    #3
    upload_to_play_store(skip_upload_apk: true, track: 'internal',
    release_status: 'draft',
    aab: '/Users/apple/vidtreon-rn-/android/app/build/outputs/bundle/release/app-release.aab')
  end
end
